### ISSUE TITLE
Problem about the sampling process.

### ISSUE THREAD

**Issue by topleo** [chrisbahnsen/aau-virada#2]
I have a problem with the videoLoader. You load 16 frames consecutive as a sample from the video file, and the stride is 8, load the label according to where the first frame is. (e.g. frame 0 to frame 15 is the first sample, frame 8 to frame 23 is the second sample.) However, a positive label means there is rain during the whole minute, not all the minute there is rain.  So, the label could be wrong?

**Comment by chrisbahnsen** [comment]
Which ground truth data are you using? The mechanical or the laser distrometer?
The mechanical tipping-gauge measurements have been quantized to 10 minute-intervals due to contractual agreements. The laser measurements, on the other hand, are provided as-is, e.g. with the highest possible accuracy
